"""added AWS

Revision ID: ad3ed109cfd6
Revises: 484459321e5f
Create Date: 2024-07-15 15:28:49.724615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3ed109cfd6'
down_revision: Union[str, None] = '484459321e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('aws_filename', sa.String(), nullable=False))
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'aws_filename')
    # ### end Alembic commands ###
